import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { Skeleton } from "@/components/ui/skeleton";
import { AIGenerationHistoryTable } from "@/components/ai/AIGenerationHistoryTable";
import { archiveCourseGeneration, archiveLessonGeneration, archiveQuizGeneration, listCourseGenerations, listLessonGenerations, listQuizGenerations, type AICourseGeneration, type AILessonGeneration, type AIQuizGeneration } from "@/lib/aiCourses";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/admin/ai-course-generations")({
  component: AICourseGenerationsPage,
});

function AICourseGenerationsPage() {
  const { isAdmin, loading } = useAuth();
  const navigate = useNavigate();
  const [courses, setCourses] = useState<AICourseGeneration[]>([]);
  const [lessons, setLessons] = useState<AILessonGeneration[]>([]);
  const [quizzes, setQuizzes] = useState<AIQuizGeneration[]>([]);
  const [busy, setBusy] = useState(true);

  useEffect(() => { if (!loading && !isAdmin) navigate({ to: "/dashboard" }); }, [loading, isAdmin, navigate]);

  const load = async () => {
    setBusy(true);
    const [c, l, q] = await Promise.all([listCourseGenerations(), listLessonGenerations(), listQuizGenerations()]);
    setCourses(c); setLessons(l); setQuizzes(q);
    setBusy(false);
  };
  useEffect(() => { if (isAdmin) load(); }, [isAdmin]);

  if (!isAdmin) return null;

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight">AI Generation History</h1>
        <p className="text-muted-foreground mt-1">Course outlines, lessons, and quizzes generated by AI. Review, open, or archive.</p>
      </header>
      {busy ? <Skeleton className="h-60" /> : (
        <AIGenerationHistoryTable
          courses={courses} lessons={lessons} quizzes={quizzes}
          onArchiveCourse={async (id) => { await archiveCourseGeneration(id); toast.success("Archived"); load(); }}
          onArchiveLesson={async (id) => { await archiveLessonGeneration(id); toast.success("Archived"); load(); }}
          onArchiveQuiz={async (id) => { await archiveQuizGeneration(id); toast.success("Archived"); load(); }}
        />
      )}
    </div>
  );
}