/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSpacesIndexRouteImport } from './routes/_authenticated/spaces.index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedSpacesSpaceIdRouteImport } from './routes/_authenticated/spaces.$spaceId'
import { Route as AuthenticatedPostsPostIdRouteImport } from './routes/_authenticated/posts.$postId'
import { Route as AuthenticatedMembersUserIdRouteImport } from './routes/_authenticated/members.$userId'
import { Route as AuthenticatedLessonsLessonIdRouteImport } from './routes/_authenticated/lessons.$lessonId'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as AuthenticatedComingSoonAreaRouteImport } from './routes/_authenticated/coming-soon.$area'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminCollectionsRouteImport } from './routes/_authenticated/admin.collections'
import { Route as AuthenticatedAdminSpacesIndexRouteImport } from './routes/_authenticated/admin.spaces.index'
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin.members.index'
import { Route as AuthenticatedAdminEventsIndexRouteImport } from './routes/_authenticated/admin.events.index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin.courses.index'
import { Route as AuthenticatedAdminSpacesSpaceIdRouteImport } from './routes/_authenticated/admin.spaces.$spaceId'
import { Route as AuthenticatedAdminMembersUserIdRouteImport } from './routes/_authenticated/admin.members.$userId'
import { Route as AuthenticatedAdminEventsEventIdRouteImport } from './routes/_authenticated/admin.events.$eventId'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated/admin.courses.$courseId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpacesIndexRoute =
  AuthenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceIdRoute =
  AuthenticatedSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsPostIdRoute =
  AuthenticatedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersUserIdRoute =
  AuthenticatedMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsLessonIdRoute =
  AuthenticatedLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComingSoonAreaRoute =
  AuthenticatedComingSoonAreaRouteImport.update({
    id: '/coming-soon/$area',
    path: '/coming-soon/$area',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCollectionsRoute =
  AuthenticatedAdminCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpacesIndexRoute =
  AuthenticatedAdminSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsIndexRoute =
  AuthenticatedAdminEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpacesSpaceIdRoute =
  AuthenticatedAdminSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersUserIdRoute =
  AuthenticatedAdminMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsEventIdRoute =
  AuthenticatedAdminEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/coming-soon/$area': typeof AuthenticatedComingSoonAreaRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/members/$userId': typeof AuthenticatedMembersUserIdRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/events/$eventId': typeof AuthenticatedAdminEventsEventIdRoute
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute
  '/admin/spaces/$spaceId': typeof AuthenticatedAdminSpacesSpaceIdRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/admin/spaces/': typeof AuthenticatedAdminSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/coming-soon/$area': typeof AuthenticatedComingSoonAreaRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/members/$userId': typeof AuthenticatedMembersUserIdRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/spaces': typeof AuthenticatedSpacesIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/events/$eventId': typeof AuthenticatedAdminEventsEventIdRoute
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute
  '/admin/spaces/$spaceId': typeof AuthenticatedAdminSpacesSpaceIdRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsIndexRoute
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute
  '/admin/spaces': typeof AuthenticatedAdminSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/coming-soon/$area': typeof AuthenticatedComingSoonAreaRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/_authenticated/members/$userId': typeof AuthenticatedMembersUserIdRoute
  '/_authenticated/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/_authenticated/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/_authenticated/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/_authenticated/admin/events/$eventId': typeof AuthenticatedAdminEventsEventIdRoute
  '/_authenticated/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute
  '/_authenticated/admin/spaces/$spaceId': typeof AuthenticatedAdminSpacesSpaceIdRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/_authenticated/admin/spaces/': typeof AuthenticatedAdminSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/feed'
    | '/profile'
    | '/settings'
    | '/admin/collections'
    | '/admin/moderation'
    | '/admin/posts'
    | '/admin/settings'
    | '/coming-soon/$area'
    | '/courses/$courseId'
    | '/events/$eventId'
    | '/lessons/$lessonId'
    | '/members/$userId'
    | '/posts/$postId'
    | '/spaces/$spaceId'
    | '/courses/'
    | '/members/'
    | '/spaces/'
    | '/admin/courses/$courseId'
    | '/admin/events/$eventId'
    | '/admin/members/$userId'
    | '/admin/spaces/$spaceId'
    | '/admin/courses/'
    | '/admin/events/'
    | '/admin/members/'
    | '/admin/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/feed'
    | '/profile'
    | '/settings'
    | '/admin/collections'
    | '/admin/moderation'
    | '/admin/posts'
    | '/admin/settings'
    | '/coming-soon/$area'
    | '/courses/$courseId'
    | '/events/$eventId'
    | '/lessons/$lessonId'
    | '/members/$userId'
    | '/posts/$postId'
    | '/spaces/$spaceId'
    | '/courses'
    | '/members'
    | '/spaces'
    | '/admin/courses/$courseId'
    | '/admin/events/$eventId'
    | '/admin/members/$userId'
    | '/admin/spaces/$spaceId'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/members'
    | '/admin/spaces'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/feed'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/admin/collections'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/settings'
    | '/_authenticated/coming-soon/$area'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/lessons/$lessonId'
    | '/_authenticated/members/$userId'
    | '/_authenticated/posts/$postId'
    | '/_authenticated/spaces/$spaceId'
    | '/_authenticated/courses/'
    | '/_authenticated/members/'
    | '/_authenticated/spaces/'
    | '/_authenticated/admin/courses/$courseId'
    | '/_authenticated/admin/events/$eventId'
    | '/_authenticated/admin/members/$userId'
    | '/_authenticated/admin/spaces/$spaceId'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/events/'
    | '/_authenticated/admin/members/'
    | '/_authenticated/admin/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spaces/': {
      id: '/_authenticated/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthenticatedSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spaces/$spaceId': {
      id: '/_authenticated/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/$postId': {
      id: '/_authenticated/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$userId': {
      id: '/_authenticated/members/$userId'
      path: '/members/$userId'
      fullPath: '/members/$userId'
      preLoaderRoute: typeof AuthenticatedMembersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$lessonId': {
      id: '/_authenticated/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coming-soon/$area': {
      id: '/_authenticated/coming-soon/$area'
      path: '/coming-soon/$area'
      fullPath: '/coming-soon/$area'
      preLoaderRoute: typeof AuthenticatedComingSoonAreaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/collections': {
      id: '/_authenticated/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spaces/': {
      id: '/_authenticated/admin/spaces/'
      path: '/spaces'
      fullPath: '/admin/spaces/'
      preLoaderRoute: typeof AuthenticatedAdminSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/': {
      id: '/_authenticated/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AuthenticatedAdminEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spaces/$spaceId': {
      id: '/_authenticated/admin/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/admin/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedAdminSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members/$userId': {
      id: '/_authenticated/admin/members/$userId'
      path: '/members/$userId'
      fullPath: '/admin/members/$userId'
      preLoaderRoute: typeof AuthenticatedAdminMembersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/$eventId': {
      id: '/_authenticated/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AuthenticatedAdminEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/$courseId': {
      id: '/_authenticated/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCollectionsRoute: typeof AuthenticatedAdminCollectionsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
  AuthenticatedAdminEventsEventIdRoute: typeof AuthenticatedAdminEventsEventIdRoute
  AuthenticatedAdminMembersUserIdRoute: typeof AuthenticatedAdminMembersUserIdRoute
  AuthenticatedAdminSpacesSpaceIdRoute: typeof AuthenticatedAdminSpacesSpaceIdRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminEventsIndexRoute: typeof AuthenticatedAdminEventsIndexRoute
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute
  AuthenticatedAdminSpacesIndexRoute: typeof AuthenticatedAdminSpacesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCollectionsRoute: AuthenticatedAdminCollectionsRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminCoursesCourseIdRoute:
    AuthenticatedAdminCoursesCourseIdRoute,
  AuthenticatedAdminEventsEventIdRoute: AuthenticatedAdminEventsEventIdRoute,
  AuthenticatedAdminMembersUserIdRoute: AuthenticatedAdminMembersUserIdRoute,
  AuthenticatedAdminSpacesSpaceIdRoute: AuthenticatedAdminSpacesSpaceIdRoute,
  AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  AuthenticatedAdminEventsIndexRoute: AuthenticatedAdminEventsIndexRoute,
  AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  AuthenticatedAdminSpacesIndexRoute: AuthenticatedAdminSpacesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedComingSoonAreaRoute: typeof AuthenticatedComingSoonAreaRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedLessonsLessonIdRoute: typeof AuthenticatedLessonsLessonIdRoute
  AuthenticatedMembersUserIdRoute: typeof AuthenticatedMembersUserIdRoute
  AuthenticatedPostsPostIdRoute: typeof AuthenticatedPostsPostIdRoute
  AuthenticatedSpacesSpaceIdRoute: typeof AuthenticatedSpacesSpaceIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedSpacesIndexRoute: typeof AuthenticatedSpacesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedComingSoonAreaRoute: AuthenticatedComingSoonAreaRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedLessonsLessonIdRoute: AuthenticatedLessonsLessonIdRoute,
  AuthenticatedMembersUserIdRoute: AuthenticatedMembersUserIdRoute,
  AuthenticatedPostsPostIdRoute: AuthenticatedPostsPostIdRoute,
  AuthenticatedSpacesSpaceIdRoute: AuthenticatedSpacesSpaceIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedSpacesIndexRoute: AuthenticatedSpacesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
